spring:
  # H2 Database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./database/mss-codi-db
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

