### 테스트 API.
GET http://localhost:8080/codi/api/category/test
Content-Type: application/json

### 테스트 API.
GET http://localhost:8080/codi/api/min-prices-category
Content-Type: application/json


### 테스트 API.
GET http://localhost:8080/codi/api/min-price
Content-Type: application/json